---

- hosts: all
  become: yes
  vars:
    version: "3.42.0-01"
    dedicated_ram: "5700m"
    nexus_systemd: |-
      [Unit]
      Description=nexus service
      After=network.target
      
      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart=/opt/nexus-{{ version }}/bin/nexus start
      ExecStop=/opt/nexus-{{ version }}/bin/nexus stop
      User=nexus
      Restart=on-abort
      Environment="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/"
      [Install]
      WantedBy=multi-user.target

  tasks:
    - name: install-java
      apt:
        name: "openjdk-8-jdk"
        state: latest
        update_cache: yes
    - name: create nexus group
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
        create_home: false
        system: true
    - name: check if nexus extracted
      stat:
        path: "/opt/nexus-{{ version }}"
      register: nexus_installed
    - name: fetch nexus tar
      unarchive:
        src: "https://download.sonatype.com/nexus/3/nexus-{{ version }}-unix.tar.gz"
        dest: /opt/
        remote_src: yes
        owner: nexus
        group: nexus
      when:
        - not nexus_installed.stat.exists
      notify: reload_systemd
    - name: set permissions
      file:
        state: directory
        path: "{{ item }}"
        recurse: yes
        owner: nexus
        group: nexus
      loop:
        - "/opt/nexus-{{ version }}/"
        - "/opt/sonatype-work"
    - name: set ram usage
      lineinfile:
        path: "/opt/nexus-{{ version }}/bin/nexus.vmoptions"
        state: present
        regexp: '^-Xms'
        line: "-Xms{{ dedicated_ram }}"
      notify: reload_systemd
    - name: set ram usage
      lineinfile:
        path: "/opt/nexus-{{ version }}/bin/nexus.vmoptions"
        state: present
        regexp: '^-Xmx'
        line: "-Xmx{{ dedicated_ram }}"
      notify: reload_systemd
    - name: create systemd unit file
      copy:
        content: "{{ nexus_systemd  }}"
        dest: "/etc/systemd/system/nexus.service"
      notify: reload_systemd
  handlers:
    - name: reload_systemd
      systemd:
        name: nexus
        state: started
        enabled: yes
        daemon_reload: yes
