---

- hosts: all
  become: yes
  vars:
    version: "3.57.0-01"
    dedicated_ram: "3800m"
    application_port: 1080
    context_path: /
    nexus_systemd: |-
      [Unit]
      Description=nexus service
      After=network.target
      
      [Service]
      Type=forking
      LimitNOFILE=65536
      ExecStart=/opt/nexus-{{ version }}/bin/nexus start
      ExecStop=/opt/nexus-{{ version }}/bin/nexus stop
      User=nexus
      Restart=on-abort
      Environment="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/"
      [Install]
      WantedBy=multi-user.target

  tasks:
    - name: install-java
      apt:
        name: "openjdk-8-jdk"
        state: latest
        update_cache: yes
    - name: create nexus group
      group:
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
        create_home: false
        system: true
    - name: check if nexus extracted
      stat:
        path: "/opt/nexus-{{ version }}"
      register: nexus_installed
    - name: fetch nexus tar
      unarchive:
        src: "https://download.sonatype.com/nexus/3/nexus-{{ version }}-unix.tar.gz"
        dest: /opt/
        remote_src: yes
        owner: nexus
        group: nexus
      when:
        - not nexus_installed.stat.exists
      notify: reload_systemd
    - name: set permissions
      file:
        state: directory
        path: "{{ item }}"
        recurse: yes
        owner: nexus
        group: nexus
      loop:
        - "/opt/nexus-{{ version }}/"
        - "/opt/sonatype-work"
    - name: set ram usage
      lineinfile:
        path: "/opt/nexus-{{ version }}/bin/nexus.vmoptions"
        state: present
        regexp: '^-Xms'
        line: "-Xms{{ dedicated_ram }}"
      notify: restart_systemd
    - name: set ram usage max
      lineinfile:
        path: "/opt/nexus-{{ version }}/bin/nexus.vmoptions"
        state: present
        regexp: '^-Xmx'
        line: "-Xmx{{ dedicated_ram }}"
      notify: restart_systemd

      #bugfix: https://support.sonatype.com/hc/en-us/articles/213464868-Nexus-Repository-2-startup-fails-with-Could-not-lock-User-prefs-Couldn-t-flush-user-prefs-Couldn-t-get-file-lock-
    - name: set user root
      lineinfile:
        path: "/opt/nexus-{{ version }}/bin/nexus.vmoptions"
        state: present
        regexp: '^-Djava.util.prefs.userRoot'
        line: "-Djava.util.prefs.userRoot=../sonatype-work/nexus3/"
      notify: restart_systemd
    - name: set app_port
      lineinfile:
        path: "/opt/nexus-{{ version }}/etc/nexus-default.properties"
        state: present
        regexp: '^application-port='
        line: "application-port={{ application_port }}"
      notify: restart_systemd
    - name: set context_path
      lineinfile:
        path: "/opt/nexus-{{ version }}/etc/nexus-default.properties"
        state: present
        regexp: '^nexus-context-path='
        line: "nexus-context-path={{ context_path }}"
      notify: restart_systemd
    - name: create systemd unit file
      copy:
        content: "{{ nexus_systemd  }}"
        dest: "/etc/systemd/system/nexus.service"
      notify: reload_systemd
    - name: Read default password
      slurp:
        src: /opt/sonatype-work/nexus3/admin.password
      register: passwd_content
    - name: Print Connection info
      debug:
        msg: "URL: {{ ansible_host }}:{{ application_port }}{{ context_path }}"
    - name: Print default password
      debug:
        msg: "Default password: {{ passwd_content.content | b64decode }}"
  handlers:
    - name: reload_systemd
      systemd:
        name: nexus
        state: started
        enabled: yes
        daemon_reload: yes
    - name: restart_systemd
      systemd:
        name: nexus
        state: restarted
